### ISSUE TITLE
Follow @Anjan50

### ISSUE THREAD

**Issue by Anjan50** [Anjan50/Python#2]
Follow @Anjan50
and add any .py file which you practiced
After you followed I merge your pull request.

**Comment by rajbhoyar729** [comment]
@anjan50   is this spam? this  is   not the  right way bro  improve the Quality of your  repos  and  projects  so people  will  automatically  follow  you  but  this  is  a  scam  bro

**Comment by Anjan50** [comment]
Closed

**Comment by Anjan50** [comment]
> @Anjan50 is this spam? this is not the right way bro improve the Quality of your repos and projects so people will automatically follow you but this is a scam bro

Closed

**Comment by rajbhoyar729** [comment]
Ha  good  please    try to  post  some thing  from that   others  can  learn  about your  projects   bro     ........ that's  the  core  vision of  hacktoberfest
